#!/usr/bin/env python3

from sources.Args import parseArgs
from sources.Gladitek import syncCalendars, clearCalendars
import sys


def main():
	try:
		args = parseArgs(sys.argv[1:])
		if args.clear:
			clearCalendars(args.gladir)
		else:
			syncCalendars(gladir=args.gladir, fullDump=args.full)
		return 0
	except Exception as e:
		raise e
		return 1

if __name__ == "__main__":
	exit(main())